package requests

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i LogWatcher/server.ClientInterface -o ./client_interface_mock_test.go

import (
	"net/http"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ClientInterfaceMock implements ClientInterface
type ClientInterfaceMock struct {
	t minimock.Tester

	funcDo          func(r *http.Request) (rp1 *http.Response, err error)
	inspectFuncDo   func(r *http.Request)
	afterDoCounter  uint64
	beforeDoCounter uint64
	DoMock          mClientInterfaceMockDo
}

// NewClientInterfaceMock returns a mock for ClientInterface
func NewClientInterfaceMock(t minimock.Tester) *ClientInterfaceMock {
	m := &ClientInterfaceMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DoMock = mClientInterfaceMockDo{mock: m}
	m.DoMock.callArgs = []*ClientInterfaceMockDoParams{}

	return m
}

type mClientInterfaceMockDo struct {
	mock               *ClientInterfaceMock
	defaultExpectation *ClientInterfaceMockDoExpectation
	expectations       []*ClientInterfaceMockDoExpectation

	callArgs []*ClientInterfaceMockDoParams
	mutex    sync.RWMutex
}

// ClientInterfaceMockDoExpectation specifies expectation struct of the ClientInterface.Do
type ClientInterfaceMockDoExpectation struct {
	mock    *ClientInterfaceMock
	params  *ClientInterfaceMockDoParams
	results *ClientInterfaceMockDoResults
	Counter uint64
}

// ClientInterfaceMockDoParams contains parameters of the ClientInterface.Do
type ClientInterfaceMockDoParams struct {
	r *http.Request
}

// ClientInterfaceMockDoResults contains results of the ClientInterface.Do
type ClientInterfaceMockDoResults struct {
	rp1 *http.Response
	err error
}

// Expect sets up expected params for ClientInterface.Do
func (mmDo *mClientInterfaceMockDo) Expect(r *http.Request) *mClientInterfaceMockDo {
	if mmDo.mock.funcDo != nil {
		mmDo.mock.t.Fatalf("ClientInterfaceMock.Do mock is already set by Set")
	}

	if mmDo.defaultExpectation == nil {
		mmDo.defaultExpectation = &ClientInterfaceMockDoExpectation{}
	}

	mmDo.defaultExpectation.params = &ClientInterfaceMockDoParams{r}
	for _, e := range mmDo.expectations {
		if minimock.Equal(e.params, mmDo.defaultExpectation.params) {
			mmDo.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDo.defaultExpectation.params)
		}
	}

	return mmDo
}

// Inspect accepts an inspector function that has same arguments as the ClientInterface.Do
func (mmDo *mClientInterfaceMockDo) Inspect(f func(r *http.Request)) *mClientInterfaceMockDo {
	if mmDo.mock.inspectFuncDo != nil {
		mmDo.mock.t.Fatalf("Inspect function is already set for ClientInterfaceMock.Do")
	}

	mmDo.mock.inspectFuncDo = f

	return mmDo
}

// Return sets up results that will be returned by ClientInterface.Do
func (mmDo *mClientInterfaceMockDo) Return(rp1 *http.Response, err error) *ClientInterfaceMock {
	if mmDo.mock.funcDo != nil {
		mmDo.mock.t.Fatalf("ClientInterfaceMock.Do mock is already set by Set")
	}

	if mmDo.defaultExpectation == nil {
		mmDo.defaultExpectation = &ClientInterfaceMockDoExpectation{mock: mmDo.mock}
	}
	mmDo.defaultExpectation.results = &ClientInterfaceMockDoResults{rp1, err}
	return mmDo.mock
}

//Set uses given function f to mock the ClientInterface.Do method
func (mmDo *mClientInterfaceMockDo) Set(f func(r *http.Request) (rp1 *http.Response, err error)) *ClientInterfaceMock {
	if mmDo.defaultExpectation != nil {
		mmDo.mock.t.Fatalf("Default expectation is already set for the ClientInterface.Do method")
	}

	if len(mmDo.expectations) > 0 {
		mmDo.mock.t.Fatalf("Some expectations are already set for the ClientInterface.Do method")
	}

	mmDo.mock.funcDo = f
	return mmDo.mock
}

// When sets expectation for the ClientInterface.Do which will trigger the result defined by the following
// Then helper
func (mmDo *mClientInterfaceMockDo) When(r *http.Request) *ClientInterfaceMockDoExpectation {
	if mmDo.mock.funcDo != nil {
		mmDo.mock.t.Fatalf("ClientInterfaceMock.Do mock is already set by Set")
	}

	expectation := &ClientInterfaceMockDoExpectation{
		mock:   mmDo.mock,
		params: &ClientInterfaceMockDoParams{r},
	}
	mmDo.expectations = append(mmDo.expectations, expectation)
	return expectation
}

// Then sets up ClientInterface.Do return parameters for the expectation previously defined by the When method
func (e *ClientInterfaceMockDoExpectation) Then(rp1 *http.Response, err error) *ClientInterfaceMock {
	e.results = &ClientInterfaceMockDoResults{rp1, err}
	return e.mock
}

// Do implements ClientInterface
func (mmDo *ClientInterfaceMock) Do(r *http.Request) (rp1 *http.Response, err error) {
	mm_atomic.AddUint64(&mmDo.beforeDoCounter, 1)
	defer mm_atomic.AddUint64(&mmDo.afterDoCounter, 1)

	if mmDo.inspectFuncDo != nil {
		mmDo.inspectFuncDo(r)
	}

	mm_params := &ClientInterfaceMockDoParams{r}

	// Record call args
	mmDo.DoMock.mutex.Lock()
	mmDo.DoMock.callArgs = append(mmDo.DoMock.callArgs, mm_params)
	mmDo.DoMock.mutex.Unlock()

	for _, e := range mmDo.DoMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.rp1, e.results.err
		}
	}

	if mmDo.DoMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDo.DoMock.defaultExpectation.Counter, 1)
		mm_want := mmDo.DoMock.defaultExpectation.params
		mm_got := ClientInterfaceMockDoParams{r}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDo.t.Errorf("ClientInterfaceMock.Do got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDo.DoMock.defaultExpectation.results
		if mm_results == nil {
			mmDo.t.Fatal("No results are set for the ClientInterfaceMock.Do")
		}
		return (*mm_results).rp1, (*mm_results).err
	}
	if mmDo.funcDo != nil {
		return mmDo.funcDo(r)
	}
	mmDo.t.Fatalf("Unexpected call to ClientInterfaceMock.Do. %v", r)
	return
}

// DoAfterCounter returns a count of finished ClientInterfaceMock.Do invocations
func (mmDo *ClientInterfaceMock) DoAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDo.afterDoCounter)
}

// DoBeforeCounter returns a count of ClientInterfaceMock.Do invocations
func (mmDo *ClientInterfaceMock) DoBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDo.beforeDoCounter)
}

// Calls returns a list of arguments used in each call to ClientInterfaceMock.Do.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDo *mClientInterfaceMockDo) Calls() []*ClientInterfaceMockDoParams {
	mmDo.mutex.RLock()

	argCopy := make([]*ClientInterfaceMockDoParams, len(mmDo.callArgs))
	copy(argCopy, mmDo.callArgs)

	mmDo.mutex.RUnlock()

	return argCopy
}

// MinimockDoDone returns true if the count of the Do invocations corresponds
// the number of defined expectations
func (m *ClientInterfaceMock) MinimockDoDone() bool {
	for _, e := range m.DoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.DoMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterDoCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDo != nil && mm_atomic.LoadUint64(&m.afterDoCounter) < 1 {
		return false
	}
	return true
}

// MinimockDoInspect logs each unmet expectation
func (m *ClientInterfaceMock) MinimockDoInspect() {
	for _, e := range m.DoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ClientInterfaceMock.Do with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.DoMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterDoCounter) < 1 {
		if m.DoMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to ClientInterfaceMock.Do")
		} else {
			m.t.Errorf("Expected call to ClientInterfaceMock.Do with params: %#v", *m.DoMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDo != nil && mm_atomic.LoadUint64(&m.afterDoCounter) < 1 {
		m.t.Error("Expected call to ClientInterfaceMock.Do")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ClientInterfaceMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockDoInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ClientInterfaceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ClientInterfaceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDoDone()
}
