package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i LogWatcher/pkg/requests.HTTPDoer -o ./pkg/mocks/http_doer_mock.go

import (
	"net/http"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// HTTPDoerMock implements requests.HTTPDoer
type HTTPDoerMock struct {
	t minimock.Tester

	funcDo          func(r *http.Request) (rp1 *http.Response, err error)
	inspectFuncDo   func(r *http.Request)
	afterDoCounter  uint64
	beforeDoCounter uint64
	DoMock          mHTTPDoerMockDo
}

// NewHTTPDoerMock returns a mock for requests.HTTPDoer
func NewHTTPDoerMock(t minimock.Tester) *HTTPDoerMock {
	m := &HTTPDoerMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DoMock = mHTTPDoerMockDo{mock: m}
	m.DoMock.callArgs = []*HTTPDoerMockDoParams{}

	return m
}

type mHTTPDoerMockDo struct {
	mock               *HTTPDoerMock
	defaultExpectation *HTTPDoerMockDoExpectation
	expectations       []*HTTPDoerMockDoExpectation

	callArgs []*HTTPDoerMockDoParams
	mutex    sync.RWMutex
}

// HTTPDoerMockDoExpectation specifies expectation struct of the HTTPDoer.Do
type HTTPDoerMockDoExpectation struct {
	mock    *HTTPDoerMock
	params  *HTTPDoerMockDoParams
	results *HTTPDoerMockDoResults
	Counter uint64
}

// HTTPDoerMockDoParams contains parameters of the HTTPDoer.Do
type HTTPDoerMockDoParams struct {
	r *http.Request
}

// HTTPDoerMockDoResults contains results of the HTTPDoer.Do
type HTTPDoerMockDoResults struct {
	rp1 *http.Response
	err error
}

// Expect sets up expected params for HTTPDoer.Do
func (mmDo *mHTTPDoerMockDo) Expect(r *http.Request) *mHTTPDoerMockDo {
	if mmDo.mock.funcDo != nil {
		mmDo.mock.t.Fatalf("HTTPDoerMock.Do mock is already set by Set")
	}

	if mmDo.defaultExpectation == nil {
		mmDo.defaultExpectation = &HTTPDoerMockDoExpectation{}
	}

	mmDo.defaultExpectation.params = &HTTPDoerMockDoParams{r}
	for _, e := range mmDo.expectations {
		if minimock.Equal(e.params, mmDo.defaultExpectation.params) {
			mmDo.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDo.defaultExpectation.params)
		}
	}

	return mmDo
}

// Inspect accepts an inspector function that has same arguments as the HTTPDoer.Do
func (mmDo *mHTTPDoerMockDo) Inspect(f func(r *http.Request)) *mHTTPDoerMockDo {
	if mmDo.mock.inspectFuncDo != nil {
		mmDo.mock.t.Fatalf("Inspect function is already set for HTTPDoerMock.Do")
	}

	mmDo.mock.inspectFuncDo = f

	return mmDo
}

// Return sets up results that will be returned by HTTPDoer.Do
func (mmDo *mHTTPDoerMockDo) Return(rp1 *http.Response, err error) *HTTPDoerMock {
	if mmDo.mock.funcDo != nil {
		mmDo.mock.t.Fatalf("HTTPDoerMock.Do mock is already set by Set")
	}

	if mmDo.defaultExpectation == nil {
		mmDo.defaultExpectation = &HTTPDoerMockDoExpectation{mock: mmDo.mock}
	}
	mmDo.defaultExpectation.results = &HTTPDoerMockDoResults{rp1, err}
	return mmDo.mock
}

//Set uses given function f to mock the HTTPDoer.Do method
func (mmDo *mHTTPDoerMockDo) Set(f func(r *http.Request) (rp1 *http.Response, err error)) *HTTPDoerMock {
	if mmDo.defaultExpectation != nil {
		mmDo.mock.t.Fatalf("Default expectation is already set for the HTTPDoer.Do method")
	}

	if len(mmDo.expectations) > 0 {
		mmDo.mock.t.Fatalf("Some expectations are already set for the HTTPDoer.Do method")
	}

	mmDo.mock.funcDo = f
	return mmDo.mock
}

// When sets expectation for the HTTPDoer.Do which will trigger the result defined by the following
// Then helper
func (mmDo *mHTTPDoerMockDo) When(r *http.Request) *HTTPDoerMockDoExpectation {
	if mmDo.mock.funcDo != nil {
		mmDo.mock.t.Fatalf("HTTPDoerMock.Do mock is already set by Set")
	}

	expectation := &HTTPDoerMockDoExpectation{
		mock:   mmDo.mock,
		params: &HTTPDoerMockDoParams{r},
	}
	mmDo.expectations = append(mmDo.expectations, expectation)
	return expectation
}

// Then sets up HTTPDoer.Do return parameters for the expectation previously defined by the When method
func (e *HTTPDoerMockDoExpectation) Then(rp1 *http.Response, err error) *HTTPDoerMock {
	e.results = &HTTPDoerMockDoResults{rp1, err}
	return e.mock
}

// Do implements requests.HTTPDoer
func (mmDo *HTTPDoerMock) Do(r *http.Request) (rp1 *http.Response, err error) {
	mm_atomic.AddUint64(&mmDo.beforeDoCounter, 1)
	defer mm_atomic.AddUint64(&mmDo.afterDoCounter, 1)

	if mmDo.inspectFuncDo != nil {
		mmDo.inspectFuncDo(r)
	}

	mm_params := &HTTPDoerMockDoParams{r}

	// Record call args
	mmDo.DoMock.mutex.Lock()
	mmDo.DoMock.callArgs = append(mmDo.DoMock.callArgs, mm_params)
	mmDo.DoMock.mutex.Unlock()

	for _, e := range mmDo.DoMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.rp1, e.results.err
		}
	}

	if mmDo.DoMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDo.DoMock.defaultExpectation.Counter, 1)
		mm_want := mmDo.DoMock.defaultExpectation.params
		mm_got := HTTPDoerMockDoParams{r}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDo.t.Errorf("HTTPDoerMock.Do got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDo.DoMock.defaultExpectation.results
		if mm_results == nil {
			mmDo.t.Fatal("No results are set for the HTTPDoerMock.Do")
		}
		return (*mm_results).rp1, (*mm_results).err
	}
	if mmDo.funcDo != nil {
		return mmDo.funcDo(r)
	}
	mmDo.t.Fatalf("Unexpected call to HTTPDoerMock.Do. %v", r)
	return
}

// DoAfterCounter returns a count of finished HTTPDoerMock.Do invocations
func (mmDo *HTTPDoerMock) DoAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDo.afterDoCounter)
}

// DoBeforeCounter returns a count of HTTPDoerMock.Do invocations
func (mmDo *HTTPDoerMock) DoBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDo.beforeDoCounter)
}

// Calls returns a list of arguments used in each call to HTTPDoerMock.Do.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDo *mHTTPDoerMockDo) Calls() []*HTTPDoerMockDoParams {
	mmDo.mutex.RLock()

	argCopy := make([]*HTTPDoerMockDoParams, len(mmDo.callArgs))
	copy(argCopy, mmDo.callArgs)

	mmDo.mutex.RUnlock()

	return argCopy
}

// MinimockDoDone returns true if the count of the Do invocations corresponds
// the number of defined expectations
func (m *HTTPDoerMock) MinimockDoDone() bool {
	for _, e := range m.DoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.DoMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterDoCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDo != nil && mm_atomic.LoadUint64(&m.afterDoCounter) < 1 {
		return false
	}
	return true
}

// MinimockDoInspect logs each unmet expectation
func (m *HTTPDoerMock) MinimockDoInspect() {
	for _, e := range m.DoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to HTTPDoerMock.Do with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.DoMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterDoCounter) < 1 {
		if m.DoMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to HTTPDoerMock.Do")
		} else {
			m.t.Errorf("Expected call to HTTPDoerMock.Do with params: %#v", *m.DoMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDo != nil && mm_atomic.LoadUint64(&m.afterDoCounter) < 1 {
		m.t.Error("Expected call to HTTPDoerMock.Do")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *HTTPDoerMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockDoInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *HTTPDoerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *HTTPDoerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDoDone()
}
