name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      e2e_log: "e2e/short.log"
      e2e_output: "received.log"
      config: "e2e/e2e_config.yaml"
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: make build-local

      - name: Dry run server
        run: ./bin/LogWatcher -config ${{ env.config }}
        timeout-minutes: 0.1

      - name: Run e2e
        run: E2E_LOG_FILE=${{ env.e2e_log }} make e2e

      - name: Compare outputs
        id: compare
        run: cmp -s ${{ env.e2e_log }} ${{ env.e2e_output }} || echo "::set-output result=true"

      - name: Check comparision
        uses: actions/github-script@v3
        if: ${{ steps.compare.outputs.result == true }}
        with:
          script: |
            core.setFailed('end2end test failed: files are different')
