name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      e2e_log: "test_client/short_test.log"
      e2e_output: "received.log"
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: make build-local

      - name: Dry run server
        run: DRY_RUN=1 ./bin/LogWatcher

      - name: Run e2e
        run: ./bin/TestClient -log ${{ env.e2e_log }} -out

      - name: Compare outputs
        id: compare
        run: cmp -s ${{ env.e2e_log }} ${{ env.e2e_output }} || echo "::set-output result=true"

      - name: Check comparision
        uses: actions/github-script@v3
        if: ${{ steps.compare.outputs.result == true }}
        with:
          script: |
            core.setFailed('end2end test failed: files are different')
