name: Build

on:
  push:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      e2e_log: "e2e/short.log"
      e2e_output: "received.log"
      config: "e2e/e2e_config.yaml"
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: make build-local

      - name: Run server and e2e test
        run: (./bin/LogWatcher -config e2e/e2e_config.yaml; exit 0) & sleep 1; ./bin/TestClient -log e2e/short.log

      - name: Compare outputs
        id: compare
        run: cmp -s ${{ env.e2e_log }} ${{ env.e2e_output }} || echo "::set-output result=false"

      - name: Exit if e2e failed
        uses: actions/github-script@v3
        if: ${{ steps.compare.outputs.result == false }}
        with:
          script: |
            core.setFailed('E2E test failed: files are different')
