name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: app
          args: --skip-files api.go

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: make build-local

      - name: Test
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage report
        run: bash <(curl -s https://codecov.io/bash)
